### ISSUE TITLE
pasteAsText interfering with insertHtml

### ISSUE THREAD

**Issue by Housi** [jakiestfu/Medium.js#119]
EDIT: There is something buggy in insertHtml behaviour but it has nothing to do with pasteAsText option

**Comment by MortimerNeuss** [comment]
Any updates on this? The parameter `pasteAsText` is not even described in detail on the [Main Page](http://jakiestfu.github.io/Medium.js/docs/#Options) (it is listed in code, but has not received a description  of detail). I'm kinda lost on how to use it correctly.
