### ISSUE TITLE
Backspace creating span

### ISSUE THREAD

**Issue by bearded-avenger** [jakiestfu/Medium.js#129]
Hey guys!
I'm getting this odd behavior where, when backspacing from a new paragraph, it creates a span tag and throws the formatting out of whack.

http://www.neotericdesign.com/blog/2013/3/working-around-chrome-s-contenteditable-span-bug

This link above is precisely what is happening. Have you guys run across this, and any recc on a way to fix for medium.js? This is the last item preventing us from moving into production. Really appreciate all the work you've all put into this!

**Comment by bearded-avenger** [comment]
I was actually able to fix this through CSS alone. Oddly enough something in the normalize.less file within Bootstrap was killing this. I replaced it entirely with a better version of a reset, and it's now fixed.

So if anyone stumbles upon this, it's something in this:
https://github.com/twbs/bootstrap/blob/master/less/normalize.less

However, this fixes it:
```
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
    display: block;
}
body {
    line-height: 1;
}
ol, ul {
    list-style: none;
}
blockquote, q {
    quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
    content: '';
    content: none;
}
table {
    border-collapse: collapse;
    border-spacing: 0;
}
```

**Comment by robertleeplummerjr** [comment]
The bearded avenger strikes again!  Thank you bearded avenger.
