### ISSUE TITLE
Paste doesn't work

### ISSUE THREAD

**Issue by Sh1nto** [jakiestfu/Medium.js#133]
I've downloaded the latest Version. Everything is fine, only paste doesn't work.

I'm Using Chrome: Version 40.0.2214.85 beta-m (64-bit)
(Also happens in current Chrome Canary)

The following errors Occur on the console:

medium.js:270 Uncaught TypeError: Cannot read property 'saveSelection' of undefinedmedium.js:270 intercept.command.pastemedium.js:185 (anonymous function)medium.js:1457 Medium.Utilities.utils.isModifiermedium.js:169 intercept.down
medium.js:431 Uncaught TypeError: Cannot read property 'saveSelection' of undefinedmedium.js:431 defaultSettings.pasteEventHandler

When debugging, utils doesn't have the property selection

**Comment by Housi** [comment]
Same here

**Comment by robertleeplummerjr** [comment]
What are the exast steps to reproduce?

**Comment by Housi** [comment]
I use Chrome 39.0.2171.99 (64-bit)

Paste doesn't work at all if pasteAsText is set to true.
Today I've updated medium.js to newest version, earlier version was ok.

**Comment by Sh1nto** [comment]
I just made a simple page:

```html
<html>
  <head>
     <title>Medium Test</title>
     <link rel="stylesheet" type="text/css" href="/data/css/medium.css">
     <script type="text/javascript" src="/data/js/medium.js"></script>

  </head>
  <body>
  <div class="contenteditable" id="cont1">
  </div>
<script type="text/javascript">
new Medium({
    element: document.getElementById('cont1'),
    mode: Medium.richMode,
    placeholder: 'Your Article',
	tags: {
		'break': 'br',
		'horizontalRule': 'hr',
		'paragraph': 'p',
		'outerLevel': ['pre', 'blockquote', 'figure', 'code', 'div'],
		'innerLevel': ['a', 'b', 'u', 'i', 'img', 'strong', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6']
		},
	attributes: {
		remove: ['style']
	}
});
</script>
</body>
</html>
```

And then try to paste something.I'm using Chrome 64bit on Windows 7. This gives the error's mentioned above.

**Comment by robertleeplummerjr** [comment]
Creating a unit test for this.  Does it matter what you paste?

On Sat, Jan 24, 2015 at 10:07 AM, Sh1nto <notifications@github.com> wrote:

> I just made a simple page:
>
> <html>
>   <head>
>      <title>Medium Test</title>
>      <link rel="stylesheet" type="text/css" href="/data/css/medium.css">     <script type="text/javascript" src="/data/js/medium.js"></script>
>
>   </head>
>   <body>
>   <div class="contenteditable" id="cont1">
>   </div><script type="text/javascript">new Medium({    element: document.getElementById('cont1'),    mode: Medium.richMode,    placeholder: 'Your Article',    tags: {        'break': 'br',        'horizontalRule': 'hr',        'paragraph': 'p',        'outerLevel': ['pre', 'blockquote', 'figure', 'code', 'div'],        'innerLevel': ['a', 'b', 'u', 'i', 'img', 'strong', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6']        },    attributes: {        remove: ['style']    }});</script>
> </body>
> </html>
>
> And then try to paste something.I'm using Chrome 64bit on Windows 7. This
> gives the error's mentioned above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakiestfu/Medium.js/issues/133#issuecomment-71321242>.
>



-- 
Robert Plummer

**Comment by Zacqary** [comment]
Firefox 36 throws a slightly different couple of errors: 
`TypeError: utils.selection is undefined        medium.js:270:13`
`TypeError: utils.selection is undefined        medium.js:431:9`

It doesn't seem to matter what I'm trying to paste.

**Comment by Sh1nto** [comment]
Doesn't matter, tried Plain Text and Richtext

**Comment by robertleeplummerjr** [comment]
Try with latest in master.

On Sat, Jan 24, 2015 at 12:33 PM, Sh1nto <notifications@github.com> wrote:

> Doesn't matter, tried Plain Text and Richtext
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakiestfu/Medium.js/issues/133#issuecomment-71328450>.
>



-- 
Robert Plummer

**Comment by Sh1nto** [comment]
The Console Error is gone. Now i get a popup with "Paste here" and a 1Line Text field.

When clicking on ok, or pressing Enter the word "undefined" is inserted. I did not typed in undefined

**Comment by jacekpl** [comment]
Paste in IE11 doesn't work. On paste I see that it's run (text is cleared from tags, I have pasteAsTest set as true), text variable is correct (https://github.com/jakiestfu/Medium.js/blob/master/medium.js#L743), but text isn't injected. I see no errors in console.

**Comment by robertleeplummerjr** [comment]
I'm going to be handling this next, FYI.

**Comment by robertleeplummerjr** [comment]
I believe #d19505cea07eb0cffaf5dd724a71cccdbcb38e0a solved this.  Can I get a yay or nay?

**Comment by kumuwai** [comment]
It does let you paste, which is good. There are a couple of oddities. First, when it finishes pasting a single line of text, the cursor ends up at the beginning of the pasted text, instead of at the end. Second, it seems to be pasting multiple lines in reverse order.

I tested with:
1. x
2. y
3. z

When I pasted into the Medium textbox, I got:

3. z
2. y
1. x

I'm running Chrome 40.0.2214.94 (64-bit) on Ubuntu. No errors in console.

**Comment by robertleeplummerjr** [comment]
Lol, wow.  I'll take a look at it asap.

**Comment by NoelBaron** [comment]
Any update on this? I'm experiencing what @kumuwai experienced regarding reversed paragraphs. Happens in Chrome consistently. Doesn't matter if pasteAsText is true or false, or if I'm pasing plain text or HTML content. Always reverses.

**Comment by darshandesai** [comment]
@robertleeplummerjr  Same here -- happens on all the demos (http://jakiestfu.github.io/Medium.js/docs/) as well (chrome + safari + firefox)

**Comment by nrkn** [comment]
This reverse paste bug is caused by inserting the elements from the end of the NodeList rather than from the start.

[Line 1754 in the master branch of medium.js](https://github.com/jakiestfu/Medium.js/blob/master/medium.js#L1754) is:

```javascript
parent.insertBefore(html[html.length - 1], wedge);
```

Should be:

```javascript
parent.insertBefore(html[0], wedge);
```
Haven't checked if this change affects anything else but cursory debugging suggests not.

**Comment by nrkn** [comment]
PS @robertleeplummerjr  didn't make a pull request because I know you guys are working on the alpha branch and I don't have the time to check the state of that, fork it, send a request etc. but hope this info helps

**Comment by robertleeplummerjr** [comment]
fork and pull master, we will take care of the rest.

On Fri, Jun 12, 2015 at 12:49 AM, Nik Coughlin <notifications@github.com>
wrote:

> PS @robertleeplummerjr <https://github.com/robertleeplummerjr> didn't
> make a pull request because I know you guys are working on the alpha branch
> and I don't have the time to check the state of that, fork it, send a
> request etc. but hope this info helps
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakiestfu/Medium.js/issues/133#issuecomment-111358383>
> .
>



-- 
Robert Plummer

**Comment by nrkn** [comment]
https://github.com/jakiestfu/Medium.js/pull/156/files

**Comment by robertleeplummerjr** [comment]
Guys, can I get at least two people confirm that
https://github.com/jakiestfu/Medium.js/pull/156#merged-event works without
regression?

**Comment by robertleeplummerjr** [comment]
Also: Nik, you rock.

**Comment by nrkn** [comment]
Thanks, and happy to help.

**Comment by nokome** [comment]
@robertleeplummerjr, not sure this is what you wanted someone to do but for what it's worth ran `test/index.html` in Chrome 43.0.2357.125 and Firefox 38.0 and *all tests passed*. Also FWIW, and a note to self, ran tests from a fresh repo like this:

```sh
git clone git@github.com:jakiestfu/Medium.js.git
cd Medium.js
bower install
sed -i "s/yui-compressor/uglifyjs/g" build
bash build
google-chrome test/index.html
firefox test/index.html
```

**Comment by Sh1nto** [comment]
Thanks for all the fixes. Inserting now works but rangy.js und undo have to be there.
