### ISSUE TITLE
Bold Italic doesn't work

### ISSUE THREAD

**Issue by Zacqary** [jakiestfu/Medium.js#134]
Using the latest version on a richMode text editor, highlighting text and doing `CMD-B` then `CMD-I` doesn't work. The text starts bold, then turns italic regular-weight, not bold-italic. Pressing `CMD-I` again to turn off italic turns the text bold (so it's definitely still bold, just being overridden by the italic).

Applying the styles in the opposite order (`CMD-I` then `CMD-B`) produces the same result, where the italic overrides the bold.

This is happening in both Firefox and Chrome on OS X.

**Comment by Zacqary** [comment]
Never mind, this is an unrelated problem with my CSS. Sorry.

**Comment by robertleeplummerjr** [comment]
it all good.
