### ISSUE TITLE
bower

### ISSUE THREAD

**Issue by TrySound** [jakiestfu/Medium.js#144]
Add main field to bower and publish it please

**Comment by robertleeplummerjr** [comment]
Is this what you mean? - https://github.com/jakiestfu/Medium.js/blob/master/bower.json#L23

**Comment by TrySound** [comment]
@robertleeplummerjr  yes, but this field must be named "main"
[Here it uses](https://github.com/ck86/main-bower-files)

**Comment by hiromitz** [comment]
and
I think testify.js should be devDependencies.
