### ISSUE TITLE
Untagging

### ISSUE THREAD

**Issue by bonfish** [jakiestfu/Medium.js#149]
And one more question: is it possible to untag a line/section/selection using Medium.js' API, as to make a button in a toolbar toggle it?

**Comment by robertleeplummerjr** [comment]
invoke handles that both on and off.

**Comment by robertleeplummerjr** [comment]
Like this:
```javascript
var m = new Medium({element: el});

//on
m.invokeElement("b", {
  title: 'My title'
});

//off
m.invokeElement("b", {
  title: 'My title'
});
```
