### ISSUE TITLE
Update bower support

### ISSUE THREAD

**Issue by zeakd** [jakiestfu/Medium.js#171]
when I Install medium with bower, 

``` bash
bower install medium
```

It automatically download #1.0.1 tag which version is not working maxLength.

so I should try 

``` bash
bower install medium#2.0.0-alpha
```

and it works.

maybe medium need another stable tag that bower can detech.

**Comment by robertleeplummerjr** [comment]
will get to this later today.

On Mon, Aug 24, 2015 at 7:51 AM, zeakd <notifications@github.com> wrote:

> when I Install medium with bower,
>
> bower install medium
>
> It automatically download #1
> <https://github.com/jakiestfu/Medium.js/pull/1>.0.1 tag which version is
> not working maxLength.
>
> so I should try
>
> bower install medium#2.0.0-alpha
>
> and it works.
>
> maybe medium need another stable tag that bower can detech.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakiestfu/Medium.js/issues/171>.
>



-- 
Robert Plummer
