### ISSUE TITLE
does medium do syntax highlighting ?

### ISSUE THREAD

**Issue by jmls** [jakiestfu/Medium.js#192]
This may be a real dumb-ass question .. but .. All I am wanting to do is to allow a user to enter html code in a textarea and have the code syntax-highlighted

I am trying to avoid big libraries like codemirror and ace, and was wondering if it would be possible using medium ?

thanks ..

**Comment by robertleeplummerjr** [comment]
No dumb questions.  I _think_ that codemirror would be more ideal in that scenario, where it is specifically a syntax highlighter, and we are more gui/contenteditable oriented.

**Comment by jmls** [comment]
thanks for the pointers, appreciate it ;) /me goes off to play with codemirror ..

**Comment by robertleeplummerjr** [comment]
👍
