### ISSUE TITLE
Click farm detected

### ISSUE THREAD

**Issue by adam-rocska** [jakiestfu/Medium.js#193]
Hi!

I just noticed that there is a clickfram link here : https://github.com/jakiestfu/Medium.js/blob/gh-pages/docs/index.html#L59

Instead of medium it points to medifum :) Thought may be handy to let you know.

**Comment by robertleeplummerjr** [comment]
And fixed: https://github.com/jakiestfu/Medium.js/commit/48592b9c0ee894d9d0b07a566cb115c486ab7b6d

Thanks!

**Comment by robertleeplummerjr** [comment]
Someone say clickfarm?!?!
![](https://media.giphy.com/media/1JyWrrkCIUQyQ/giphy.gif)
