### ISSUE TITLE
Duplication of same content with insertHtml

### ISSUE THREAD

**Issue by arifhussain353** [jakiestfu/Medium.js#210]
**Description**
When user `keypress` `space` i get content and save it to some variable. Then i replaced some content in saved string and `set` to `medium` again.

**Expected**
Content should replace and overwrite to old content.

**Issue**
After `space` `keypress` same content is copied and paste along with old content. Even if i press `space` key multiple time.

**Live Example**
[jsfiddle](http://jsfiddle.net/arifhussain/xpvt214o/984547/)

**Comment by arifhussain353** [comment]
No update for this issue? @robertleeplummerjr

**Comment by robertleeplummerjr** [comment]
No, I've been MIA for some time on other priorities and family.  Would this be something you would be interested in submitting a PR on?
