### ISSUE TITLE
Can I use custom classes inside contenteditable?

### ISSUE THREAD

**Issue by alinnert** [jakiestfu/Medium.js#57]
Hello,
Is it possible to add classes to some paragraphs?
My idea is to implement some very basic "Syntax Highlighting". Therefore I need to change the classes of some paragraph elements. But when I do that the class gets removed immediately.
How can I do that?

**Comment by Beppe** [comment]
just a note 
```
medium.invokeElement('p', {
  'class': 'custom-class-here'
});
```
should be

```
medium.invokeElement('p', {
  'className': 'custom-class-here'
});
```
