### ISSUE TITLE
Undo.js and rangy

### ISSUE THREAD

**Issue by hanssnabilie** [jakiestfu/Medium.js#78]
It is unclear which undo.js and rangy versions need to be included. In the bower package I found:
		"rangy": "https://github.com/jackcviers/Rangy",
		"undo": "https://github.com/jzaefferer/undo" 

However rangy's current version can be found here https://github.com/timdown/rangy. Undo seems quite old and inactive. Is it possible to update the website bit about this ("domesticated: when undo.js & rangy are included before Medium.js, domesticated behavior is triggered...") to be clear about the versions one has to use?

**Comment by robertleeplummerjr** [comment]
versions have been added to help with this.
