### ISSUE TITLE
NPM Module ?

### ISSUE THREAD

**Issue by antoniobrandao** [jakiestfu/Medium.js#83]
Would be great if this awesomeness was available in NPM, using CommonJS format to quickly plug into NPM-managed projects.

**Comment by antoniobrandao** [comment]
Great stuff guys, thank you all. Since this has been implemented, I suppose I can close this Issue. A great 2015 for all of you !

**Comment by robertleeplummerjr** [comment]
* high fives team*

On Thu, Jan 1, 2015 at 4:49 PM, Antonio Brandao <notifications@github.com>
wrote:

> Great stuff guys, thank you all. Since this has been implemented, I
> suppose I can close this Issue. A great 2015 for all of you !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakiestfu/Medium.js/issues/83#issuecomment-68499461>.
>



-- 
Robert Plummer
