### ISSUE TITLE
Rangy JS Error report

### ISSUE THREAD

**Issue by antoniobrandao** [jakiestfu/Medium.js#86]
I would just like to report Rangy is throwing an error about Discontiguous Selection in the Docs page. I'm not sure which Medium.js instance is causing it. This happens everytime after a full refresh in my Chrome, without touching anything.

Here is a screenshot:

http://cl.ly/image/0M1h3n2E1p0q

**Comment by robertleeplummerjr** [comment]
There is no actual error.  So closing.
